/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LaunchRouteImport } from './routes/launch'
import { Route as CallRecordingsRouteImport } from './routes/call-recordings'
import { Route as ArtifactsRouteImport } from './routes/artifacts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects/$projectId'
import { Route as HelpCreditReportRouteImport } from './routes/help/credit-report'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchRoute = LaunchRouteImport.update({
  id: '/launch',
  path: '/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const CallRecordingsRoute = CallRecordingsRouteImport.update({
  id: '/call-recordings',
  path: '/call-recordings',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsRoute = ArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpCreditReportRoute = HelpCreditReportRouteImport.update({
  id: '/help/credit-report',
  path: '/help/credit-report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/call-recordings': typeof CallRecordingsRoute
  '/launch': typeof LaunchRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/help/credit-report': typeof HelpCreditReportRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/call-recordings': typeof CallRecordingsRoute
  '/launch': typeof LaunchRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/help/credit-report': typeof HelpCreditReportRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artifacts': typeof ArtifactsRoute
  '/call-recordings': typeof CallRecordingsRoute
  '/launch': typeof LaunchRoute
  '/settings': typeof SettingsRoute
  '/test': typeof TestRoute
  '/help/credit-report': typeof HelpCreditReportRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artifacts'
    | '/call-recordings'
    | '/launch'
    | '/settings'
    | '/test'
    | '/help/credit-report'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artifacts'
    | '/call-recordings'
    | '/launch'
    | '/settings'
    | '/test'
    | '/help/credit-report'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/artifacts'
    | '/call-recordings'
    | '/launch'
    | '/settings'
    | '/test'
    | '/help/credit-report'
    | '/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtifactsRoute: typeof ArtifactsRoute
  CallRecordingsRoute: typeof CallRecordingsRoute
  LaunchRoute: typeof LaunchRoute
  SettingsRoute: typeof SettingsRoute
  TestRoute: typeof TestRoute
  HelpCreditReportRoute: typeof HelpCreditReportRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launch': {
      id: '/launch'
      path: '/launch'
      fullPath: '/launch'
      preLoaderRoute: typeof LaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/call-recordings': {
      id: '/call-recordings'
      path: '/call-recordings'
      fullPath: '/call-recordings'
      preLoaderRoute: typeof CallRecordingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts': {
      id: '/artifacts'
      path: '/artifacts'
      fullPath: '/artifacts'
      preLoaderRoute: typeof ArtifactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/credit-report': {
      id: '/help/credit-report'
      path: '/help/credit-report'
      fullPath: '/help/credit-report'
      preLoaderRoute: typeof HelpCreditReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtifactsRoute: ArtifactsRoute,
  CallRecordingsRoute: CallRecordingsRoute,
  LaunchRoute: LaunchRoute,
  SettingsRoute: SettingsRoute,
  TestRoute: TestRoute,
  HelpCreditReportRoute: HelpCreditReportRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
