NOVA_2_LITE = "global.amazon.nova-2-lite-v1:0"

SUPERVISOR_MODEL_ID = NOVA_2_LITE
REPORT_MODEL_ID = NOVA_2_LITE
RESEARCH_MODEL_ID = NOVA_2_LITE
PLAN_MODEL_ID = NOVA_2_LITE
WRITE_MODEL_ID = NOVA_2_LITE
